abstract: Kwiki HatenaAuth integration
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Kwiki-HatenaAuth
no_index: 
  directory: 
    - inc
    - t
requires: 
  Hatena::API::Auth: 0.03
  URI::Escape: 0
version: 0.02
